### ISSUE TITLE
Cannot feed value of shape (126,) which has shape '(128,)'

### ISSUE THREAD

**Issue by orangeqqq** [biomedia-mira/masf#3]
Dear @carrenD ,

Thanks for sharing the great work.

However, I had the following error when running the code.

```python
Traceback (most recent call last):
  File "main.py", line 245, in <module>
    main()
  File "main.py", line 242, in main
    train(model, saver, sess, exp_string, train_file_list, test_file_list[0], resume_itr)
  File "main.py", line 153, in train
    _, _, _, summ_writer, global_loss, source_loss, source_accuracy, metric_loss = sess.run(output_tensors, feed_dict)
  File "C:\anaconda3\envs\tensorf\lib\site-packages\tensorflow\python\client\session.py", line 950, in run
    run_metadata_ptr)
  File "C:\anaconda3\envs\tensorf\lib\site-packages\tensorflow\python\client\session.py", line 1149, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (126,) for Tensor 'Placeholder_9:0', which has shape '(128,)'
```

Could you tell me how should i deal with the problem?

Looking forward to your reply.

Best regards,
Yuntao

**Comment by carrenD** [comment]
Hi Yuntao, it seems there is some mismatch in your batchsize or input image size. Try to set as 128 instead of 126

**Comment by orangeqqq** [comment]
yes,it's mismatch of batchsize.Thank you very much
